---
- name: Ensure target directory exists
  delegate_to: '{{ etcd_build_host }}'
  file:
    dest: '{{ etcd_build_path }}'
    state: directory

- name: Checkout Git repo
  delegate_to: '{{ etcd_build_host }}'
  git:
    repo: '{{ etcd_build_repo_url }}'
    dest: '{{ etcd_build_path }}'
    update: '{{ etcd_build_repo_update }}'
    version: '{{ etcd_build_version | default(etcd_build_version_default) }}'
  register: etcd_git_result

- name: Check if binary is build already
  delegate_to: '{{ etcd_build_host }}'
  run_once: true
  stat:
    path: '{{ etcd_build_bin_path }}/{{ etcd_etcd_binary_file_name }}'
  register: etcd_binary_file

- name: Build binaries
  delegate_to: '{{ etcd_build_host }}'
  run_once: true
  shell: '{{ etcd_build_path }}/build'
  args:
    chdir: '{{ etcd_build_path }}'
  when: not etcd_binary_file.stat.exists or etcd_git_result.changed