---
- name: Ensure build packages
  sudo: true
  yum:
    name: '{{ item }}'
    state: present
  with_items: etcd_build_packages
  when: etcd_build_install_packages

- name: Ensure build directory
  file:
    dest: '{{ etcd_build_path }}'
    state: directory

- name: Checkout Git repo
  git:
    repo: '{{ etcd_build_repo_url }}'
    dest: '{{ etcd_build_path }}'
    update: '{{ etcd_build_repo_update }}'
    version: '{{ etcd_build_version | default(etcd_build_version_default) }}'
  register: etcd_git_result

- name: Check if binary is build already
  stat:
    path: '{{ etcd_build_bin_path }}/{{ etcd_etcd_binary_file_name }}'
  register: etcd_binary_file

- name: Build binaries
  shell: '{{ etcd_build_path }}/build'
  args:
    chdir: '{{ etcd_build_path }}'
  when: not etcd_binary_file.stat.exists or etcd_git_result.changed