---
- name: Fetch binaries from build host
  connection: local
  delegate_to: '{{ etcd_build_host }}'
  fetch:
    src: '{{ item }}'
    dest: /tmp
  with_items:
  - '{{ etcd_etcd_binary_file }}'
  - '{{ etcd_etcdctl_binary_file }}'

- name: Ensure etcd binary
  copy:
    src: /tmp/{{ etcd_build_host }}/{{ etcd_etcd_binary_file }}
    dest: '{{ etcd_install_path }}/{{ etcd_etcd_binary_file_name }}'
    mode: '{{ etcd_install_mode }}'
    owner: '{{ etcd_install_owner }}'
    group: '{{ etcd_install_group }}'

- name: Ensure etcdctl binary
  copy:
    src: /tmp/{{ etcd_build_host }}/{{ etcd_etcdctl_binary_file }}
    dest: '{{ etcd_install_path }}/{{ etcd_etcdctl_binary_file_name }}'
    owner: '{{ etcd_install_owner }}'
    group: '{{ etcd_install_group }}'
    mode: '{{ etcd_install_mode }}'

- name: Ensure service file
  template:
    src: '{{ etcd_service_file_template }}'
    dest: '{{ etcd_service_file_path }}/{{ etcd_service_file_name }}'
    mode: '{{ etcd_service_file_mode }}'
  tags: service
  notify: restart etcd

- name: Ensure service is running and configured to start on boot
  service:
    name: '{{ etcd_service_name }}'
    state: '{{ etcd_service_state }}'
    enabled: '{{ etcd_service_enabled }}'
  tags: service