---
- name: Ensure etcd binary
  sudo: true
  copy:
    src: '{{ etcd_build_bin_path}}/{{ etcd_etcd_binary_file_name }}'
    dest: '{{ etcd_install_path }}/{{ etcd_etcd_binary_file_name }}'
    mode: '{{ etcd_install_mode }}'
    owner: '{{ etcd_install_owner }}'
    group: '{{ etcd_install_group }}'

- name: Ensure etcdctl binary
  sudo: true
  copy:
    src: '{{ etcd_build_bin_path }}/{{ etcd_etcdctl_binary_file_name }}'
    dest: '{{ etcd_install_path }}/{{ etcd_etcdctl_binary_file_name }}'
    owner: '{{ etcd_install_owner }}'
    group: '{{ etcd_install_group }}'
    mode: '{{ etcd_install_mode }}'