---
- include_vars: '{{ ansible_os_family }}{{ ansible_distribution_major_version }}.yml'
  tags:
  - build
  - install
  - service

- include: build.yml
  when: etcd_build
  tags: build

- include: install.yml
  when: etcd_install
  tags: install