---
- include: build.yml
  when: etcd_build
  tags: build

- include: install.yml
  when: etcd_install
  tags: install

- include: service.yml
  when: etcd_install_systemd_service or etcd_install_sysvinit_service
  tags: service