---
- include_vars: systemd.yml
  when: etcd_install_systemd_service

- include_vars: sysvinit.yml
  when: etcd_install_sysvinit_service

- name: Ensure service file
  template:
    src: '{{ etcd_service_file_template }}'
    dest: '{{ etcd_service_file_path }}/{{ etcd_service_file_name }}'
    mode: '{{ etcd_service_file_mode }}'
  notify: restart etcd

- name: Ensure service is running and configured to start on boot
  service:
    name: '{{ etcd_service_name }}'
    state: '{{ etcd_service_state }}'
    enabled: '{{ etcd_service_enabled }}'